### ISSUE TITLE
reLaunch on Mac

### ISSUE THREAD

**Issue by Daandelange** [videodromm/netdromm#19]
Hey,
On Mac (10.12) I can launch netdromm only once.
Launched with `cd /path/to/netdromm && npm start`.
When I exit (quit Terminal or `ctrl + c`) then relaunch it, it fails starting.
The error mentions `Error: listen EADDRINUSE` so it looks like the listener doesn't unbind listening correctly, resulting in the port not being available forever.
For now, the only solution I found is to restart my computer.
Is this only related to Mac ? Any idea on how to shut it down correctly ?

**Comment by jarpi** [comment]
Hey, 

It seems a problem related to how npm is handling system termination signals, see this [issue](https://github.com/npm/npm/issues/4603), it's quite similar at what we are experiencing. 
That's why it's not happening with nodemon or just nodejs. 
As a work around try this [PR](https://github.com/videodromm/netdromm/pull/20)

**Comment by Daandelange** [comment]
Thanks, gonna try that :)
Another temp fix I found is `killall -9 node`.

**Comment by Daandelange** [comment]
Thanks, issue resolved, closing this issue :)
